### ISSUE TITLE
Alert warning

### ISSUE THREAD

**Issue by joelpittet** [ubc-web-services/Megatron#41]
There doesn't seem to be styles for the warning status in the CLF
http://clf.ubc.ca/design-specifications/components.html#alerts

The warning they give an example for is very similar to the alert.

Any chance we can make one up?

Something like this:

![components___ubc_clf__common_look_and_feel_](https://cloud.githubusercontent.com/assets/70129/19208417/65809610-8cae-11e6-9957-34a6de4ac43c.png)

**Comment by occupant** [comment]
I don't find the styles for these to be very good - the titles and links often have strange colours. 

I use these most of the time (with error / danger and info / status sharing a style):
![screen shot 2016-10-11 at 10 18 11 am](https://cloud.githubusercontent.com/assets/130125/19280861/61a32ce2-8f9c-11e6-800d-cb209ee6d20a.png)
 I'm happy to add these, but I think it should be a set of opt in styles since we're clearly off CLF.

**Comment by joelpittet** [comment]
Those look way better! I agree about the clash color titles. Maybe we can add as an alternative? Like add a theme setting and class in preprocess?

**Comment by occupant** [comment]
Sure, I can add a theme setting, then add the additional css file if needed. It uses all the same markup, so I don't think I'll need the preprocess class.

**Comment by joelpittet** [comment]
What do you think about keeping the colors to match the CLF as much as possible, and remove the rounded corners?  I'm not sure how much to push the colors but maybe something like this would work? Feel free to play with the colors, I used tints and complements of existing colors.

https://jsfiddle.net/q8qLe4y8/

**Comment by joelpittet** [comment]
I can make a PR if you think this would work?

**Comment by occupant** [comment]
That sounds great. I've been meaning to get to this but it's always last on the list :)
