### ISSUE TITLE
LESS

### ISSUE THREAD

**Issue by darko-hrgovic** [ubc-web-services/Megatron#57]
We might think about standardizing LESS in develop branch. For example, off.canvas.drawer.less exists, but navigation.sticky.less does not.

We might also suggest a standard approach to minification in README.md, like less-plugin-clean-css

**Comment by joelpittet** [comment]
I'm for standardizing the LESS files, but personally prefer to move to SASS, but +1 for standardizing.

Regarding minification though, I'd suggest we don't minify and let Drupal do that.

**Comment by darko-hrgovic** [comment]
+1 on all counts

Jens prefers to keep the grad css uncompiled, but the Megatron would be good as SASS (like your basic theme :-). I came across it as LESS and continued down that road. The drawer css would need to be ported to SASS in that case.

**Comment by darko-hrgovic** [comment]
How about a gulp config, too? (again, like in basic theme :-)

**Comment by occupant** [comment]
Yes, it would be good to port everything to sass - we’ve already moved that way in galactus. And we’ve dropped minification, so it makes sense to do that here too. 

For the sass compiling / autoprefixing, Joel added yarn to galactus instead of a gulp / grunt process. I haven’t really worked with it yet, but I’d suggest that that as an alternative to gulp. And, to add to the list, I’d love to get some linting in here.

**Comment by darko-hrgovic** [comment]
Love it. 

Since I'm new to this party, wondering who is doing what with Megatron/Galactus at this point?

And James, aren't you on holiday? ;-)  Enjoy!

**Comment by joelpittet** [comment]
Anybody is doing anything if they can:)

Here's the PR for SASS https://github.com/ubc-web-services/galactus/pull/17

You'll see the yarn scripts to help reduce dependencies on ecosystems of task runner wrappers like gulp/grunt/etc.  I'm following this general philosophy https://medium.freecodecamp.org/why-i-left-gulp-and-grunt-for-npm-scripts-3d6853dd22b8

**Comment by occupant** [comment]
This is in now (at least as a start). Only took a year! hah 
f69198a
